# Generated by Django 4.1 on 2023-12-04 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='website',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='address',
            new_name='salutation',
        ),
    ]
